#' Write configurations to _deploy.yml or DESCRIPTION
#'
#' dployr execution can be controlled through the use of a `_deploy.yml` file
#' in the projects root or by setting the same values in the `Config/deploy`
#' field of the projects `DESCRIPTION` file. The priority of settings are
#' `_deploy.yml` > `DESCRIPTION` > defaults. `config_set()` allow you to write
#' configuration values to either of these places. `config_get` retrieves the
#' configuration for the current project (by default merging all sources
#' together).
#'
#' ## Recognised settings
#' The following list provides an overview of the settings that are currently
#' used by dployr:
#'
#' - `distDir`: The location of files generated by static projects. Defaults to
#'   `./dist/`.
#' - `port`: The port to use for dynamic projects. Defaults to `50505`.
#' - `host`: The host to use for dynamic projects. Defaults to `"127.0.0.1"`.
#' - `workerId`: An ID that identifies the specific worker running the code.
#'   Will be used by Shiny runtimes to correctly route clients to the same
#'   worker. Defaults to `""`.
#' - `sharedSecret`: A shared secret used by Plumber, plumber2 and Shiny as a
#'   simple authentication mechanism. Defaults to `NULL`.
#' - `logger`: The name of the R package used for logging by the server.
#'   Currently unused. Defaults to `"logger"`.
#' - `staticFormat`: The format to render to for static projects. Is passed to
#'   `output_format` in quarto and rmarkdown rendering pipelines. Defaults to
#'   `NULL`
#' - `params`: A list of parameters to overwrite in the YAML front-matter of
#'   quarto and rmarkdown documents. Will be passed to
#'   `quarto::quarto_render(execute_params)` and `rmarkdown::render(params)`.
#'   Defaults to `list()`
#' - `quartoArgs`: Additional arguments for quarto, passed to
#'   `quarto::quarto_render(quarto_args)`. Defaults to `NULL`
#' - `pandocArgs`: Additional arguments for quarto, passed to
#'   `quarto::quarto_render(pandoc_args)`. Defaults to `NULL`
#' - `hugoArgs`: Additional arguments for blogdown, passed to
#'   `blogdown::build_site(hugo_args)`. Defaults to `NULL`
#'
#' @param ... Named values to write to the configuration
#' @param .in The location to write the configuration to or read it from. For
#' `config_get()` multiple values are allowed and the values from the sources
#' will be merged together according to the priority in the description.
#'
#' @return This function is called for its side effect
#'
#' @export
#' @rdname config
#' @name config
#'
config_set <- function(..., .in = c("deploy", "desc")) {
  match.arg(.in)
  config <- list(...)
  if (.in == "deploy") {
    config <- utils::modifyList(config_get("deploy"), config)
    yaml::write_yaml(config, "_deploy.yml")
  } else if (.in == "desc") {
    config <- utils::modifyList(config_get("desc"), config)
    config <- deparse(config)
    desc <- as.data.frame(read.dcf("DESCRIPTION"))
    desc[["Config/deploy"]] <- config
    write.dcf(desc, "DESCRIPTION")
  }
}

#' @rdname config
#' @export
config_get <- function(.in = c("default", "desc", "deploy")) {
  proj_conf <- if ("default" %in% .in) config_default() else list()
  if ("desc" %in% .in) {
    desc_config <- read.dcf("DESCRIPTION", fields = "Config/deploy")
    if (!is.na(desc_config)) {
      proj_conf <- utils::modifyList(proj_conf, eval(parse(text = desc_config)))
    }
  }
  if ("deploy" %in% .in) {
    if (file.exists("_deploy.yml")) {
      proj_conf <- utils::modifyList(proj_conf, yaml::read_yaml("_deploy.yml"))
    }
  }
  proj_conf
}

config_default <- function() {
  list(
    distDir = "dist",
    port = 50505,
    host = "127.0.0.1",
    workerId = "",
    sharedSecret = NULL,
    logger = "logger",
    staticFormat = NULL,
    params = list(),
    quartoArgs = NULL,
    pandocArgs = NULL,
    hugoArgs = NULL
  )
}
